"""Structural NLP helpers for tinyNLP."""

from tinynlp.nlp.assembly import (
    AssemblyContract,
    AssemblyError,
    AssemblyProvenance,
    CoordinateEntry,
    JacobianAssemblyTerm,
    ResidualAssembly,
    ResidualAssemblyTerm,
    ResidualValue,
    SparseMatrixAssembly,
    assemble_jacobian,
    assemble_residuals,
    build_assembly_contract,
    format_assembly_contract,
    format_residual_assembly,
    format_sparse_matrix,
    to_dense,
)
from tinynlp.nlp.modeling import (
    VariableArray,
    merge_value_maps,
    residual_block,
    sum_expressions,
    variable_array,
)
from tinynlp.nlp.problem import Problem, ResidualBlock, ResidualKind
from tinynlp.nlp.sparsity import (
    SparsityEntry,
    SparsityPattern,
    SparsityTraceEvent,
    expression_dependencies,
    format_sparsity,
    jacobian_sparsity,
)

__all__ = [
    "AssemblyError",
    "AssemblyContract",
    "AssemblyProvenance",
    "CoordinateEntry",
    "JacobianAssemblyTerm",
    "Problem",
    "ResidualAssembly",
    "ResidualAssemblyTerm",
    "ResidualBlock",
    "ResidualKind",
    "ResidualValue",
    "SparseMatrixAssembly",
    "SparsityEntry",
    "SparsityPattern",
    "SparsityTraceEvent",
    "VariableArray",
    "assemble_jacobian",
    "assemble_residuals",
    "build_assembly_contract",
    "expression_dependencies",
    "format_assembly_contract",
    "format_residual_assembly",
    "format_sparsity",
    "format_sparse_matrix",
    "jacobian_sparsity",
    "merge_value_maps",
    "residual_block",
    "sum_expressions",
    "to_dense",
    "variable_array",
]
