"""KKT, reference linear-solve, and prototype solver helpers for tinyNLP."""

from tinynlp.solvers.constrained import (
    IterationRecord,
    SolverError,
    SolverResult,
    SolverStatus,
    VariableValue,
    format_solver_trace,
    solve_constraints,
)
from tinynlp.solvers.kkt import (
    KKTBlock,
    KKTBlockKind,
    KKTEntry,
    KKTError,
    KKTProvenance,
    KKTSystem,
    build_kkt_system,
    format_kkt_system,
    kkt_to_dense,
)
from tinynlp.solvers.least_squares import (
    LeastSquaresError,
    LeastSquaresIterationRecord,
    LeastSquaresResult,
    LeastSquaresStatus,
    NormalEquationSystem,
    format_least_squares_trace,
    format_normal_equations,
    solve_least_squares,
)
from tinynlp.solvers.linear import (
    DenseReferenceLinearSolver,
    LinearSolveError,
    LinearSolver,
    LinearSolveResult,
)
from tinynlp.solvers.sensitivity import (
    SensitivityEntry,
    SensitivityError,
    SensitivityResult,
    SensitivityRhsEntry,
    SensitivityTrace,
    format_sensitivity,
    implicit_sensitivity,
)

__all__ = [
    "DenseReferenceLinearSolver",
    "IterationRecord",
    "KKTBlock",
    "KKTBlockKind",
    "KKTEntry",
    "KKTError",
    "KKTProvenance",
    "KKTSystem",
    "LeastSquaresError",
    "LeastSquaresIterationRecord",
    "LeastSquaresResult",
    "LeastSquaresStatus",
    "LinearSolveError",
    "LinearSolveResult",
    "LinearSolver",
    "NormalEquationSystem",
    "SensitivityEntry",
    "SensitivityError",
    "SensitivityResult",
    "SensitivityRhsEntry",
    "SensitivityTrace",
    "SolverError",
    "SolverResult",
    "SolverStatus",
    "VariableValue",
    "build_kkt_system",
    "format_least_squares_trace",
    "format_normal_equations",
    "format_sensitivity",
    "format_solver_trace",
    "implicit_sensitivity",
    "format_kkt_system",
    "kkt_to_dense",
    "solve_constraints",
    "solve_least_squares",
]
